import { Express } from 'express';
import { healthRouter } from './health';
import { authRouter } from './modules/auth';
import { schoolsRouter } from './modules/schools';
import { studentsRouter } from './modules/students';
import { subjectsRouter } from './modules/subjects';
import { assessmentsRouter } from './modules/assessments';
import { examsRouter } from './modules/exams';
import { attendanceRouter } from './modules/attendance';
import { resultsRouter } from './modules/results';
import { usersRouter } from './modules/users';
import { schemesRouter } from './modules/schemes';
import { announcementsRouter } from './modules/announcements';
import { proctoringRouter } from './modules/proctoring';
import { liveClassesRouter } from './modules/liveClasses';
import { aiActivityRouter } from './modules/aiActivity';
import { aiActivitySmokeRouter } from './modules/aiActivitySmoke';
import { libraryRouter } from './modules/library';

export const registerRoutes = (app: Express) => {
  app.use('/api/health', healthRouter);
  app.use('/api/auth', authRouter);
  app.use('/api/schools', schoolsRouter);
  app.use('/api/users', usersRouter);
  app.use('/api/students', studentsRouter);
  app.use('/api/subjects', subjectsRouter);
  app.use('/api/assessments', assessmentsRouter);
  app.use('/api/results', resultsRouter);
  app.use('/api/exams', examsRouter);
  app.use('/api/attendance', attendanceRouter);
  app.use('/api/schemes', schemesRouter);
  app.use('/api/announcements', announcementsRouter);
  app.use('/api/proctoring', proctoringRouter);
  app.use('/api/live-classes', liveClassesRouter);
app.use('/api/ai-activity', aiActivityRouter);
  app.use('/api/ai-activity', aiActivitySmokeRouter);
  app.use('/api/library', libraryRouter);
};
